
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDrightNOTAND LPAREN NOT OR RPAREN VAR\n    calc : expression\n         | term\n    \n    expression : expression OR term\n               | term\n    \n    term : term AND factor\n         | factor\n    \n    factor : NOT factor\n           | primary\n    \n    primary : LPAREN expression RPAREN\n            | VAR\n    '
    
_lr_action_items = {'NOT':([0,5,7,9,10,],[5,5,5,5,5,]),'LPAREN':([0,5,7,9,10,],[7,7,7,7,7,]),'VAR':([0,5,7,9,10,],[8,8,8,8,8,]),'$end':([1,2,3,4,6,8,11,14,15,16,],[0,-1,-2,-6,-8,-10,-7,-3,-5,-9,]),'OR':([2,3,4,6,8,11,12,13,14,15,16,],[9,-4,-6,-8,-10,-7,9,-4,-3,-5,-9,]),'AND':([3,4,6,8,11,13,14,15,16,],[10,-6,-8,-10,-7,10,10,-5,-9,]),'RPAREN':([4,6,8,11,12,13,14,15,16,],[-6,-8,-10,-7,16,-4,-3,-5,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'calc':([0,],[1,]),'expression':([0,7,],[2,12,]),'term':([0,7,9,],[3,13,14,]),'factor':([0,5,7,9,10,],[4,11,4,4,15,]),'primary':([0,5,7,9,10,],[6,6,6,6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> calc","S'",1,None,None,None),
  ('calc -> expression','calc',1,'p_calc','par_project.py',45),
  ('calc -> term','calc',1,'p_calc','par_project.py',46),
  ('expression -> expression OR term','expression',3,'p_expression_or','par_project.py',52),
  ('expression -> term','expression',1,'p_expression_or','par_project.py',53),
  ('term -> term AND factor','term',3,'p_term_and','par_project.py',62),
  ('term -> factor','term',1,'p_term_and','par_project.py',63),
  ('factor -> NOT factor','factor',2,'p_factor_not','par_project.py',72),
  ('factor -> primary','factor',1,'p_factor_not','par_project.py',73),
  ('primary -> LPAREN expression RPAREN','primary',3,'p_primary','par_project.py',82),
  ('primary -> VAR','primary',1,'p_primary','par_project.py',83),
]
